<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Admin extends MY_Controller {
 public function __construct(){parent::__construct();$this->require_admin();}
 private function page($view,$data=array()){$this->render('admin/'.$view,$data,'layouts/admin');}
 public function dashboard(){$this->page('dashboard',array('title'=>'Operations overview','metrics'=>$this->Bank_model->admin_metrics(),'volume'=>$this->Bank_model->transaction_volume_7d(),'distribution'=>$this->Bank_model->account_distribution(),'customers'=>$this->Bank_model->customers(5),'transactions'=>$this->Bank_model->all_transactions(NULL,6)));}
 public function customers(){$q=$this->input->get('q',TRUE);$this->page('customers',array('title'=>'Customers','customers'=>$this->Bank_model->customers(100,$q),'q'=>$q));}
 public function customer($id){$customer=$this->Bank_model->customer_detail((int)$id);if(!$customer)show_404();$this->page('customer_detail',array('title'=>$customer['first_name'].' '.$customer['last_name'],'customer'=>$customer));}
 public function kyc($id){if($this->input->method()!=='post')show_404();$status=$this->input->post('kyc_status',TRUE);if($this->Bank_model->update_kyc_status((int)$id,$status)){$this->Bank_model->audit('kyc_updated','Customer #'.$id.' KYC set to '.$status,$this->user['id']);$this->session->set_flashdata('success','KYC status updated.');}else $this->session->set_flashdata('error','Invalid KYC status.');redirect('admin/customers/'.$id);}
 public function customer_create(){
  if($this->input->method()==='post'){
   $this->form_validation->set_rules('first_name','First name','required|trim|max_length[80]');$this->form_validation->set_rules('last_name','Last name','required|trim|max_length[80]');$this->form_validation->set_rules('username','Username','required|trim|is_unique[users.username]');$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[users.email]');$this->form_validation->set_rules('password','Temporary password','required|min_length[8]');$this->form_validation->set_rules('opening_balance','Opening balance','required|numeric|greater_than_equal_to[0]');
   if($this->form_validation->run()){$id=$this->Bank_model->create_customer(array('first_name'=>$this->input->post('first_name',TRUE),'last_name'=>$this->input->post('last_name',TRUE),'username'=>$this->input->post('username',TRUE),'email'=>$this->input->post('email',TRUE),'password'=>$this->input->post('password'),'phone'=>$this->input->post('phone',TRUE),'country'=>$this->input->post('country',TRUE),'opening_balance'=>$this->input->post('opening_balance')));if($id){$this->Bank_model->audit('customer_created','Customer #'.$id.' created',$this->user['id']);if(function_exists('notify_user')){try{notify_user($id,'Welcome to NorthWest','<p>Hi '.htmlspecialchars($this->input->post('first_name',TRUE)).',</p><p>Your NorthWest account has been created. You can now sign in to online banking and manage your money.</p>','');}catch(Exception $e){}}$this->session->set_flashdata('success','Customer account created.');redirect('admin/customers/'.$id);}}
   $this->session->set_flashdata('error',validation_errors('',' '));redirect('admin/customers/create');
  }
  $this->page('customer_form',array('title'=>'Create customer'));
 }
 public function customer_status($id){if($this->input->method()!=='post')show_404();$status=$this->input->post('status',TRUE);if($this->Bank_model->update_customer_status((int)$id,$status)){$this->Bank_model->audit('customer_status','Customer #'.$id.' set to '.$status,$this->user['id']);$this->session->set_flashdata('success','Customer status updated.');}else $this->session->set_flashdata('error','Invalid customer status.');redirect('admin/customers/'.$id);}
 public function customer_adjust($id){if($this->input->method()!=='post')show_404();$this->form_validation->set_rules('account_id','Account','required|integer');$this->form_validation->set_rules('amount','Amount','required|numeric|greater_than[0]');$this->form_validation->set_rules('direction','Direction','required|in_list[credit,debit]');if($this->form_validation->run()){list($ok,$message)=$this->Bank_model->adjust_balance($this->input->post('account_id'),(int)$id,$this->input->post('amount'),$this->input->post('direction',TRUE),$this->input->post('note',TRUE));if($ok){$this->Bank_model->audit('balance_adjustment',$message.' on customer #'.$id,$this->user['id']);$this->session->set_flashdata('success','Balance adjusted. Reference: '.$message);}else $this->session->set_flashdata('error',$message);}else $this->session->set_flashdata('error',validation_errors('',' '));redirect('admin/customers/'.$id);}
 public function transactions(){$this->page('transactions',array('title'=>'Transactions','heading'=>'All transactions','transactions'=>$this->Bank_model->all_transactions(),'kind'=>''));}
 public function transfers(){$this->page('transactions',array('title'=>'Transfers','heading'=>'Transfer operations','transactions'=>$this->Bank_model->all_transactions('transfers'),'kind'=>'transfers'));}
 public function deposits(){$this->page('transactions',array('title'=>'Deposits','heading'=>'Deposit operations','transactions'=>$this->Bank_model->all_transactions('deposits'),'kind'=>'deposits'));}
 public function export_transactions($kind=NULL){$rows=$this->Bank_model->all_transactions($kind,5000);$name='northwest-transactions-'.date('Y-m-d').'.csv';$this->output->set_content_type('text/csv')->set_header('Content-Disposition: attachment; filename="'.$name.'"');$out=fopen('php://output','w');fputcsv($out,array('Date','Reference','Customer','Category','Type','Amount','Currency','Status'));foreach($rows as $t){fputcsv($out,array($t['transaction_date'],$t['reference'],($t['first_name']??'').' '.($t['last_name']??''),$t['category'],$t['type'],$t['amount'],$t['currency'],$t['status']));}fclose($out);}
 public function transaction_status($id){if($this->input->method()!=='post')show_404();$status=$this->input->post('status',TRUE);if($this->Bank_model->set_transaction_status((int)$id,$status)){$this->Bank_model->audit('transaction_status','Transaction #'.$id.' set to '.$status,$this->user['id']);$this->session->set_flashdata('success','Transaction updated.');}redirect($this->input->server('HTTP_REFERER') ?: 'admin/transactions');}
 public function loans(){if($this->input->method()==='post'){$this->form_validation->set_rules('user_id','Customer','required|integer');$this->form_validation->set_rules('amount','Amount','required|numeric|greater_than[0]');$this->form_validation->set_rules('term_months','Term','required|integer');if($this->form_validation->run()){list($ok,$message)=$this->Bank_model->admin_issue_loan(array('user_id'=>$this->input->post('user_id'),'type'=>$this->input->post('type',TRUE),'amount'=>$this->input->post('amount'),'term_months'=>$this->input->post('term_months'),'interest_rate'=>$this->input->post('interest_rate')));if($ok){$this->Bank_model->audit('loan_issued','Loan '.$message.' issued to customer #'.$this->input->post('user_id'),$this->user['id']);$this->session->set_flashdata('success','Loan issued. Reference: '.$message);}else $this->session->set_flashdata('error',$message);}else $this->session->set_flashdata('error',validation_errors('',' '));redirect('admin/loans');}$this->page('loans',array('title'=>'Loan management','loans'=>$this->Bank_model->all_loans(),'customers'=>$this->Bank_model->customers(200)));}
 public function cards(){$this->page('cards',array('title'=>'Card management','cards'=>$this->Bank_model->all_cards()));}
 public function tickets(){$this->page('tickets',array('title'=>'Support tickets','tickets'=>$this->Bank_model->tickets()));}
 public function ticket($id){$ticket=$this->Bank_model->ticket((int)$id);if(!$ticket)show_404();$this->page('ticket_detail',array('title'=>$ticket['subject'],'ticket'=>$ticket));}
 public function ticket_reply($id){if($this->input->method()!=='post')show_404();$this->form_validation->set_rules('message','Reply','required|trim|max_length[5000]');if($this->form_validation->run() && $this->Bank_model->reply_ticket((int)$id,$this->user['id'],$this->input->post('message',TRUE),$this->input->post('status',TRUE))){$this->Bank_model->audit('ticket_reply','Replied to ticket #'.$id,$this->user['id']);$this->session->set_flashdata('success','Reply added.');}else $this->session->set_flashdata('error',validation_errors('',' ') ?: 'Unable to add reply.');redirect('admin/tickets/'.$id);}
 public function tutorial(){$this->page('tutorial',array('title'=>'Platform tutorial'));}
 public function audit_logs(){$q=$this->input->get('q',TRUE);$this->page('audit_logs',array('title'=>'Audit log','logs'=>$this->Bank_model->audit_log(200,$q),'q'=>$q));}
 public function admin_users(){
  if($this->input->method()==='post'){
   $this->form_validation->set_rules('first_name','First name','required|trim|max_length[80]');$this->form_validation->set_rules('last_name','Last name','required|trim|max_length[80]');
   $this->form_validation->set_rules('username','Username','required|trim|is_unique[users.username]');$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[users.email]');$this->form_validation->set_rules('password','Password','required|min_length[8]');
   if($this->form_validation->run()){$this->Bank_model->create_admin(array('first_name'=>$this->input->post('first_name',TRUE),'last_name'=>$this->input->post('last_name',TRUE),'username'=>$this->input->post('username',TRUE),'email'=>$this->input->post('email',TRUE),'password'=>$this->input->post('password')));$this->Bank_model->audit('admin_created','Administrator '.$this->input->post('username',TRUE).' created',$this->user['id']);$this->session->set_flashdata('success','Administrator created.');}
   else $this->session->set_flashdata('error',validation_errors('',' '));redirect('admin/admin_users');
  }
  $this->page('admin_users',array('title'=>'Admin users','admins'=>$this->Bank_model->admins()));
 }
 public function settings(){if($this->input->method()==='post'){$keys=array('institution_name','support_email','default_currency','daily_transfer_limit','session_timeout','registration_enabled','announcement_text','seo_site_name','seo_title','seo_description','seo_keywords');$values=array();foreach($keys as $k){$v=$this->input->post($k,TRUE);if($v!==NULL)$values[$k]=$v;}if($values){$this->Bank_model->save_settings($values);$this->Bank_model->audit('settings_updated','System settings updated',$this->user['id']);$this->session->set_flashdata('success','System settings saved.');}else $this->session->set_flashdata('error','No settings were submitted.');redirect('admin/settings');}$this->page('settings',array('title'=>'System settings','settings'=>$this->Bank_model->settings()));}
}
