<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Admin extends MY_Controller {
 public function __construct(){parent::__construct();$this->require_admin();}
 private function page($view,$data=array()){$this->render('admin/'.$view,$data,'layouts/admin');}
 public function dashboard(){$this->page('dashboard',array('title'=>'Operations overview','metrics'=>$this->Bank_model->admin_metrics(),'customers'=>$this->Bank_model->customers(5),'transactions'=>$this->Bank_model->all_transactions(NULL,6)));}
 public function customers(){$this->page('customers',array('title'=>'Customers','customers'=>$this->Bank_model->customers()));}
 public function customer($id){$customer=$this->Bank_model->customer_detail((int)$id);if(!$customer)show_404();$this->page('customer_detail',array('title'=>$customer['first_name'].' '.$customer['last_name'],'customer'=>$customer));}
 public function customer_create(){
  if($this->input->method()==='post'){
   $this->form_validation->set_rules('first_name','First name','required|trim|max_length[80]');$this->form_validation->set_rules('last_name','Last name','required|trim|max_length[80]');$this->form_validation->set_rules('username','Username','required|trim|is_unique[users.username]');$this->form_validation->set_rules('email','Email','required|valid_email|is_unique[users.email]');$this->form_validation->set_rules('password','Temporary password','required|min_length[8]');$this->form_validation->set_rules('opening_balance','Opening balance','required|numeric|greater_than_equal_to[0]');
   if($this->form_validation->run()){$id=$this->Bank_model->create_customer(array('first_name'=>$this->input->post('first_name',TRUE),'last_name'=>$this->input->post('last_name',TRUE),'username'=>$this->input->post('username',TRUE),'email'=>$this->input->post('email',TRUE),'password'=>$this->input->post('password'),'phone'=>$this->input->post('phone',TRUE),'country'=>$this->input->post('country',TRUE),'opening_balance'=>$this->input->post('opening_balance')));if($id){$this->Bank_model->audit('customer_created','Customer #'.$id.' created',$this->user['id']);$this->session->set_flashdata('success','Customer account created.');redirect('admin/customers/'.$id);}}
   $this->session->set_flashdata('error',validation_errors('',' '));redirect('admin/customers/create');
  }
  $this->page('customer_form',array('title'=>'Create customer'));
 }
 public function customer_status($id){if($this->input->method()!=='post')show_404();$status=$this->input->post('status',TRUE);if($this->Bank_model->update_customer_status((int)$id,$status)){$this->Bank_model->audit('customer_status','Customer #'.$id.' set to '.$status,$this->user['id']);$this->session->set_flashdata('success','Customer status updated.');}else $this->session->set_flashdata('error','Invalid customer status.');redirect('admin/customers/'.$id);}
 public function customer_adjust($id){if($this->input->method()!=='post')show_404();$this->form_validation->set_rules('account_id','Account','required|integer');$this->form_validation->set_rules('amount','Amount','required|numeric|greater_than[0]');$this->form_validation->set_rules('direction','Direction','required|in_list[credit,debit]');if($this->form_validation->run()){list($ok,$message)=$this->Bank_model->adjust_balance($this->input->post('account_id'),(int)$id,$this->input->post('amount'),$this->input->post('direction',TRUE),$this->input->post('note',TRUE));if($ok){$this->Bank_model->audit('balance_adjustment',$message.' on customer #'.$id,$this->user['id']);$this->session->set_flashdata('success','Balance adjusted. Reference: '.$message);}else $this->session->set_flashdata('error',$message);}else $this->session->set_flashdata('error',validation_errors('',' '));redirect('admin/customers/'.$id);}
 public function transactions(){$this->page('transactions',array('title'=>'Transactions','heading'=>'All transactions','transactions'=>$this->Bank_model->all_transactions()));}
 public function transfers(){$this->page('transactions',array('title'=>'Transfers','heading'=>'Transfer operations','transactions'=>$this->Bank_model->all_transactions('transfers')));}
 public function deposits(){$this->page('transactions',array('title'=>'Deposits','heading'=>'Deposit operations','transactions'=>$this->Bank_model->all_transactions('deposits')));}
 public function transaction_status($id){if($this->input->method()!=='post')show_404();$status=$this->input->post('status',TRUE);if($this->Bank_model->set_transaction_status((int)$id,$status)){$this->Bank_model->audit('transaction_status','Transaction #'.$id.' set to '.$status,$this->user['id']);$this->session->set_flashdata('success','Transaction updated.');}redirect($this->input->server('HTTP_REFERER') ?: 'admin/transactions');}
 public function loans(){$this->page('loans',array('title'=>'Loan management','loans'=>$this->Bank_model->all_loans()));}
 public function cards(){$this->page('cards',array('title'=>'Card management','cards'=>$this->Bank_model->all_cards()));}
 public function tickets(){$this->page('tickets',array('title'=>'Support tickets','tickets'=>$this->Bank_model->tickets()));}
 public function ticket($id){$ticket=$this->Bank_model->ticket((int)$id);if(!$ticket)show_404();$this->page('ticket_detail',array('title'=>$ticket['subject'],'ticket'=>$ticket));}
 public function ticket_reply($id){if($this->input->method()!=='post')show_404();$this->form_validation->set_rules('message','Reply','required|trim|max_length[5000]');if($this->form_validation->run() && $this->Bank_model->reply_ticket((int)$id,$this->user['id'],$this->input->post('message',TRUE),$this->input->post('status',TRUE))){$this->Bank_model->audit('ticket_reply','Replied to ticket #'.$id,$this->user['id']);$this->session->set_flashdata('success','Reply added.');}else $this->session->set_flashdata('error',validation_errors('',' ') ?: 'Unable to add reply.');redirect('admin/tickets/'.$id);}
 public function tutorial(){$this->page('tutorial',array('title'=>'Platform tutorial'));}
 public function settings(){if($this->input->method()==='post'){$keys=array('institution_name','support_email','default_currency','daily_transfer_limit','session_timeout','announcement_text','seo_site_name','seo_title','seo_description','seo_keywords');$values=array();foreach($keys as $k){$v=$this->input->post($k,TRUE);if($v!==NULL)$values[$k]=$v;}if($values){$this->Bank_model->save_settings($values);$this->Bank_model->audit('settings_updated','System settings updated',$this->user['id']);$this->session->set_flashdata('success','System settings saved.');}else $this->session->set_flashdata('error','No settings were submitted.');redirect('admin/settings');}$this->page('settings',array('title'=>'System settings','settings'=>$this->Bank_model->settings()));}
}
