<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Profile extends MY_Controller {
 public function __construct(){parent::__construct();$this->require_customer();}
 public function index(){if($this->input->method()==='post'){$this->form_validation->set_rules('first_name','First name','required|trim|max_length[80]');$this->form_validation->set_rules('last_name','Last name','required|trim|max_length[80]');$this->form_validation->set_rules('email','Email','required|valid_email');if($this->form_validation->run()){$profile_data=array('phone'=>$this->input->post('phone',TRUE),'address'=>$this->input->post('address',TRUE),'city'=>$this->input->post('city',TRUE),'country'=>$this->input->post('country',TRUE),'updated_at'=>date('Y-m-d H:i:s'));if(!empty($_FILES['avatar']['name'])){$relative=trim($this->config->item('upload_path'),'/\\\\');$upload_path=preg_match('#^([A-Za-z]:)?[\\\\\\\\/]#',$relative)?$relative:FCPATH.$relative;$this->load->library('upload',array('upload_path'=>$upload_path,'allowed_types'=>'jpg|jpeg|png|webp','max_size'=>$this->config->item('max_upload_kb'),'encrypt_name'=>TRUE,'remove_spaces'=>TRUE));if(!$this->upload->do_upload('avatar')){$this->session->set_flashdata('error',strip_tags($this->upload->display_errors('',' ')));redirect('settings');}$file=$this->upload->data();$profile_data['avatar_path']=$relative.'/'.$file['file_name'];}$this->Bank_model->update_profile($this->user['id'],array('first_name'=>$this->input->post('first_name',TRUE),'last_name'=>$this->input->post('last_name',TRUE),'email'=>$this->input->post('email',TRUE),'updated_at'=>date('Y-m-d H:i:s')),$profile_data);$this->session->set_flashdata('success','Profile updated.');}else $this->session->set_flashdata('error',validation_errors('',' '));redirect('settings');}$this->render('customer/settings',array('title'=>'Settings','profile'=>$this->Bank_model->profile($this->user['id']),'preferences'=>$this->Bank_model->preferences($this->user['id'])));}
 public function preferences(){if($this->input->method()!=='post')redirect('settings');$keys=array('notify_transfers','notify_tickets','notify_security','email_alerts','language','region');foreach($keys as $k){$v=$this->input->post($k,TRUE);$this->Bank_model->set_preference($this->user['id'],$k,$v);}if($this->input->post('language',TRUE))$this->session->set_userdata('language',$this->input->post('language',TRUE));$this->Bank_model->audit('preferences_updated','Notification and region preferences updated',$this->user['id']);$this->session->set_flashdata('success','Preferences saved.');redirect('settings');}
 public function password(){if($this->input->method()!=='post')redirect('settings');$this->form_validation->set_rules('current_password','Current password','required');$this->form_validation->set_rules('new_password','New password','required|min_length[8]');$this->form_validation->set_rules('confirm_new','Confirm password','required|matches[new_password]');if($this->form_validation->run() && $this->Bank_model->change_password($this->user['id'],$this->input->post('current_password'),$this->input->post('new_password'))){$this->Bank_model->audit('password_changed','Password changed by user',$this->user['id']);$this->session->set_flashdata('success','Your password has been updated.');}else $this->session->set_flashdata('error',validation_errors('',' ') ?: 'Your current password is incorrect.');redirect('settings');}
 public function twofa(){if($this->input->method()!=='post')redirect('settings');$enabled=$this->input->post('twofa_enabled')==='1';$this->Bank_model->set_twofa($this->user['id'],$enabled);$this->Bank_model->audit('twofa_updated','Two-factor authentication '.($enabled?'enabled':'disabled'),$this->user['id']);$this->session->set_flashdata('success','Two-factor authentication '.($enabled?'enabled':'disabled').'.');redirect('settings');}
}
